DROP DATABASE IF EXISTS AlBye;

CREATE DATABASE AlBye
USE AlBye;

CREATE TABLE Users(
    USER VARCHAR(100) PRIMARY NOT NULL,
    PW VARCHAR(100),
    EMAIL VARCHAR(100) NOT NULL,,
    FLAG INT DEFAULT 0,
    AUTHKEY VARCHAR(100),
    NICKNAME VARCHAR(100)
);

CREATE TABLE Restaurent(
   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   TEL VARCHAR(100),
   RESNAME VARCHAR(100),
   ADDR VARCHAR(100),
   LONGI VARCHAR(100),
   LATI VARCHAR(100)
);

CREATE TABLE Menu(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    RESID INT,
    MNAME VARCHAR(100)
);


CREATE TABLE Allergys(
    ALLERGY VARCHAR(100),
    USER VARCHAR(1000) NOT NULL
);
